# Generated by Django 4.2.3 on 2023-07-13 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='grading_app/media')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Selected_Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=1, max_digits=3)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading_app.parameter')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Input_grade_name', max_length=100)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading_app.commodity')),
                ('selected_parameters', models.ManyToManyField(to='grading_app.selected_parameter')),
            ],
        ),
        migrations.AddField(
            model_name='commodity',
            name='parameters',
            field=models.ManyToManyField(to='grading_app.selected_parameter'),
        ),
    ]
