# Generated by Django 4.2.3 on 2023-07-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
