# Generated by Django 4.2.3 on 2023-07-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
