# Generated by Django 4.2.3 on 2023-07-14 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grading_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GradeParameterValue',
            new_name='GradeParameter',
        ),
    ]
