# Generated by Django 4.2.3 on 2023-07-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading_app', '0002_grade_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='grading_app/media'),
        ),
    ]
