# Generated by Django 4.2.3 on 2023-07-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading_app', '0002_rename_gradeparametervalue_gradeparameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gradeparameter',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
