# Generated by Django 4.2.3 on 2023-07-13 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grading_app', '0003_alter_commodity_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='value',
            name='parameter',
        ),
    ]
