# Generated by Django 4.2.3 on 2023-07-14 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading_app', '0003_grade_is_active_gradeparameter_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='commodity',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='grade_parameter',
        ),
        migrations.AddField(
            model_name='grade',
            name='grade_parameter',
            field=models.ManyToManyField(to='grading_app.gradeparameter'),
        ),
    ]
