# Generated by Django 4.2.3 on 2023-07-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading_app', '0004_remove_value_parameter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodityparameter',
            name='value',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='value',
        ),
        migrations.AddField(
            model_name='commodityparameter',
            name='Parameter_value',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='grade',
            name='value_range',
            field=models.CharField(default='input_value_range', max_length=20),
        ),
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(default='Input_name', max_length=10),
        ),
        migrations.DeleteModel(
            name='Value',
        ),
    ]
