# Generated by Django 4.2.3 on 2023-07-14 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grading_app', '0004_remove_grade_commodity_remove_grade_grade_parameter_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Grade',
            new_name='CommodityGrade',
        ),
    ]
