# Generated by Django 4.2.3 on 2023-07-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading_app', '0004_remove_commoditygrade_grade_parameters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commoditygrade',
            name='grade_parameter',
        ),
        migrations.AddField(
            model_name='commoditygrade',
            name='grade_parameters',
            field=models.ManyToManyField(related_name='commodity_grades', to='grading_app.gradeparameter'),
        ),
    ]
