# Generated by Django 4.2.3 on 2023-07-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading_app', '0005_remove_commodityparameter_value_remove_grade_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='name',
            field=models.CharField(default='Input_grade_name', max_length=100),
        ),
        migrations.AlterField(
            model_name='grade',
            name='value_range',
            field=models.CharField(default='input_parameter_value_range', max_length=100),
        ),
    ]
