# Generated by Django 4.2.3 on 2023-07-14 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grading_app', '0005_rename_grade_commoditygrade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commoditygrade',
            name='grade_parameter',
        ),
        migrations.AddField(
            model_name='commoditygrade',
            name='grade_parameter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='grading_app.gradeparameter'),
        ),
    ]
